---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "github action updates"

  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "pip updates"
    ignore:
      - dependency-name: "mypy"
        update-types: ["version-update:semver-major"]
